In [3]:
# EXERCICIO 01

import pandas as pd

serie_vazia = pd.Series()
print("Tipo de dado da Series vazia:", serie_vazia.dtype)

Tipo de dado da Series vazia: object

In [3]:
# EXERCICIO 02

frutas = ["Maçã", "Banana", "Laranja", "Uva", "Manga"]
serie_frutas = pd.Series(frutas)
print("\nSérie de Frutas:")
print(serie_frutas)

Série de Frutas:
0       Maçã
1     Banana
2    Laranja
3        Uva
4      Manga
dtype: str

In [4]:
# EXERCICIO 03

import numpy as np

valores = np.array([10, 20, 30, 40])
serie_numpy = pd.Series(valores,
index=['A', 'B', 'C', 'D'])

print("Series criadas a partir de um array Numpy:")
print(serie_numpy)

Series criadas a partir de um array Numpy:
A    10
B    20
C    30
D    40
dtype: int64

In [8]:
# EXERCICIO 04

dicionario = {'jan': 100, 'fev': 200}

serie_dic = pd.Series(dicionario,
index=['jan', 'fev', 'mar'])

print(serie_dic)

jan    100.0
fev    200.0
mar      NaN
dtype: float64

In [6]:
# EXERCICIO 05

pd.DataFrame(data=None, index=None,
columns=None, dtype=None, copy=None)

Empty DataFrame
Columns: []
Index: []

In [7]:
data = {'Name': ['João', 'Maria', 'Pedro', 'Ana', ], 'Age':[25, 30, 35, 20]}
df = pd.DataFrame(data)
df

    Name  Age
0   João   25
1  Maria   30
2  Pedro   35
3    Ana   20

In [10]:
df = pd.DataFrame(data, index=['rank1', 'rank2', 'rank3', 'rank4'])
df

        Name  Age
rank1   João   25
rank2  Maria   30
rank3  Pedro   35
rank4    Ana   20

In [32]:
data = [{'a':1, 'b':2}, {'c': 5}, {'c':8, 'd':10}]
df = pd.DataFrame(data)
df

     a    b    c     d
0  1.0  2.0  NaN   NaN
1  NaN  NaN  5.0   NaN
2  NaN  NaN  8.0  10.0

In [33]:
data = [{'a':1, 'b':2,'c': 5}, {'c':8, 'd':10}]
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])
df2 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b1'])

df1
df2

          a  b1
first   1.0 NaN
second  NaN NaN

In [34]:
dados = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
         'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(dados)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [35]:
df['three'] = pd.Series([10., 20., 30.], index=['a', 'b', 'c'])
df

   one  two  three
a  1.0  1.0   10.0
b  2.0  2.0   20.0
c  3.0  3.0   30.0
d  NaN  4.0    NaN

In [30]:
del df['two']
df

   one  three
a  1.0   10.0
b  2.0   20.0
c  3.0   30.0
d  NaN    NaN

In [36]:
df.pop('three')
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0