In [1]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient('mongodb://localhost:27017/')
filter = {}

result = client['banco_music']['music'].find(
    filter=filter
)

df = pd.DataFrame(list(result))

display(df)

,_id,musica,artista,album,data_lancamento
0,69c31744066cc4f7e2940eb7,my mind is a mountain,Deftones,private music,2025-08-22
1,69c31744066cc4f7e2940eb8,locked club,Deftones,private music,2025-08-22
2,69c31744066cc4f7e2940eb9,ecdysis,Deftones,private music,2025-08-22
3,69c31744066cc4f7e2940eba,infinite source,Deftones,private music,2025-08-22
4,69c31744066cc4f7e2940ebb,souvenir,Deftones,private music,2025-08-22
...,...,...,...,...,...
475,69c31744066cc4f7e2941092,Counterfeit - Lethal Dose Extreme Guitar Mix (...,Limp Bizkit,New Old Songs,2001-01-01
476,69c31744066cc4f7e2941093,Rollin' - DJ Monk-Vs-The Track Mack Remix (Exp...,Limp Bizkit,New Old Songs,2001-01-01
477,69c31744066cc4f7e2941094,My Way - DJ Premier Way Remix - Expicit,Limp Bizkit,New Old Songs,2001-01-01
478,69c31744066cc4f7e2941095,My Way - William Orbit's Mix - Explicit,Limp Bizkit,New Old Songs,2001-01-01
479,69c31744066cc4f7e2941096,My Way - Pistols' Dancehall Dub (Album Version),Limp Bizkit,New Old Songs,2001-01-01

In [2]:
db = client['banco_music']
colecao = db['music']

dados = list(colecao.find().limit(5))

df = pd.DataFrame(dados)
display(df.head())

,_id,musica,artista,album,data_lancamento
0,69c31744066cc4f7e2940eb7,my mind is a mountain,Deftones,private music,2025-08-22
1,69c31744066cc4f7e2940eb8,locked club,Deftones,private music,2025-08-22
2,69c31744066cc4f7e2940eb9,ecdysis,Deftones,private music,2025-08-22
3,69c31744066cc4f7e2940eba,infinite source,Deftones,private music,2025-08-22
4,69c31744066cc4f7e2940ebb,souvenir,Deftones,private music,2025-08-22